# Require user permission
sudo: required

# Travis CI will install a copy of Docker
services:
  - docker

before_install:
  - docker build -t lduonghcm/docker-react -f Dockerfile.dev .

# Option -e CI=true allow quit the test after finish running
# No need to wait for input after the test
script:
  - docker run -e CI=true lduonghcm/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  # region is created when we create elasticbeanstalk
  # use the domain link on AWS
  region: "ap-southeast-2"
  app: "docker-react"
  env: "Docker-react-env"
  # bucket is a zip file that Travis CI used to deploy onto AWS
  bucket_name: "elasticbeanstalk-ap-southeast-2-420804195267"
  # usually the path is the same as the app name when created
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"